
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_GO_DespachoXCliente

    Public Property oaccbnumi As Integer

    Public Property ccnumi As Integer

    Public Property cccod As String

    Public Property ccdesc As String

    Public Property oacnrofact As Long

    Public Property obptot As Nullable(Of Decimal)

    Public Property obdesc As Nullable(Of Decimal)

    Public Property obtotal As Nullable(Of Decimal)

    Public Property IdZona As Nullable(Of Integer)

    Public Property oaest As Nullable(Of Integer)

    Public Property oaap As Nullable(Of Integer)

    Public Property oafdoc As Nullable(Of Date)

    Public Property oanumi As Integer


End Class
